language: php

php:
  - 7.0
install:
  - composer self-update
  - composer install --no-interaction

before_script:
#  - chmod 777 -R storage
  - cp .env.testing .env
  - touch database/database.sqlite
  - php artisan key:generate
  - php -S localhost:8000 -t public &
  - sleep 5

script:
  - vendor/bin/codecept run acceptance