language: php

php:
  - 7.0

install:
  - cp .env.dusk .env
  - touch database/laravel_chat.sqlite
  - chmod 775 -R storage/
#  - mysql -e 'create database laravel_chat;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
#  - php artisan migrate

before_script:
   - phantomjs --webdriver=127.0.0.1:9515 & # Start PhantomJS driver
   - php artisan serve & # Start server
   - sleep 5 # Give PhantomJS and Artisan time to start

script:
  - vendor/bin/phpunit
  - php artisan dusk