language: php

php:
  - 7.0

before_install:
#  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
#  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
#  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
#  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - npm install phantomjs

before_script:
  - chmod 777 -R storage
  - cp .env.dusk .env
  - touch database/laravel_chat.sqlite
#  - mysql -e 'create database laravel_chat;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  #  - php artisan migrate
  - phantomjs --webdriver=localhost:4444 & # Start PhantomJS driver
  - php artisan serve & # Start server
  - sleep 5 # Give PhantomJS and Artisan time to start

script:
  - vendor/bin/phpunit
  - php artisan dusk