language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - cp .env.example .env.dusk
  - cp .env.example .env
  - touch database/laravel_chat.sqlite
  - mysql -e 'create database laravel_chat;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_script:
   - phantomjs --webdriver=127.0.0.1:9515 & # Start PhantomJS driver
   - php artisan serve & # Start server
   - sleep 5 # Give PhantomJS and Artisan time to start

script:
  - vendor/bin/phpunit
  - php artisan dusk