language: php

php:
  - 7.0

before_script:
#  - chmod 777 -R storage
#  - cp .env.dusk .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - php -S localhost:8000 -t public
  - vendor/bin/codecept run acceptance